name: PHP Security Checker

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        id: cache-db
        with:
            path: ~/.symfony/cache
            key: db

      - name: Allow pests
        run: composer config --no-plugins allow-plugins.pestphp/pest-plugin true

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: The PHP Security Checker
        uses: symfonycorp/security-checker-action@v2
